server:
  port: 8034
spring:
  freemarker:
    suffix: .html
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    content-type: text/html
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB