server:
  port: 49810

spring:
  application:
    name: apigw

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:40791/eureka/

zuul:
  retryable: true
  routes:
    susys:
      path: /susys/**
      service-id: susys
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 6000